[tool.pysen]
version = "0.11.0"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = false

[tool.pysen.lint.source]
exclude_globs = ["**/__init__.py"]

[tool.pytest.ini_options]
addopts = "-s -v"
markers = [
    "utility"
]
describe_prefixes = ["describe_", "context_"]