services:
  api:
    container_name: visionai-api
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    env_file:
      - .env.prob
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
