version: "3.8"

services:
  visionai-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    environment:
      - PYTHONUNBUFFERED=1
    command: sleep infinity 
